set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)

vcpkg_from_github(
  OUT_SOURCE_PATH
  SOURCE_PATH
  REPO
  matterfi/casper-cpp-sdk
  REF
  1aeee9a5ad33688dde464e67c7f34c3f9dd25e20
  SHA512
  bb9c0bdef278b6168452ba78cae0bf37fedf8dd83337bbafedea85fac3488e84eb3943cadd660224be191de3c956036ce81b242da994bd644bb75eae4cd58b6d
  HEAD_REF
  main
)

vcpkg_cmake_configure(
  SOURCE_PATH
  "${SOURCE_PATH}"
  OPTIONS
  -DCASPERSDK_BUILD_TESTS=OFF
  -DCASPERSDK_MULTICONFIG=OFF
  OPTIONS_RELEASE
  -DCASPERSDK_DEBUG_BUILD=OFF
  -DCASPERSDK_INSTALL_LICENSE=ON
  -DCASPERSDK_LICENSE_FILE_NAME=copyright
  OPTIONS_DEBUG
  -DCASPERSDK_DEBUG_BUILD=ON
  -DCASPERSDK_PEDANTIC_BUILD=OFF
  -DCASPERSDK_INSTALL_HEADERS=OFF
  -DCASPERSDK_INSTALL_LICENSE=OFF
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(
  PACKAGE_NAME
  "CasperSDK"
  NO_PREFIX_CORRECTION
)

file(
  INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage"
  DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
)
