name: automerge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enable_automerge:
      runs-on: ubuntu-latest
      steps:
        - name: Enable Pull Request Automerge
          run: gh pr merge --merge --auto "1"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
